### ISSUE TITLE
Allow high resolution mode for I2C communication

### ISSUE THREAD

**Issue by partofthething** [Seeed-Studio/Seeed_Arduino_LIS3DHTR#2]
I noticed that when I connect to this device with the I2C communication protocol I get low-resolution (2 decimal) values. I would like to get more decimals. Looking at the code, I see the constructor with I2C passes the `LIS3DHTR_REG_ACCEL_CTRL_REG4_HS_DISABLE` flag. Can we make this configurable by the user to choose high-res for I2C?

**Comment by Pillar1989** [comment]
That's a good question. @LynnL4 Can you try it? Just in time to verify it on WT.

**Comment by LynnL4** [comment]
Hi @partofthething 
You can use ```LIS.sethighsolution (true)``` to control high resolution in the latest version.
