### ISSUE TITLE
Please release a new version of LIS3DHTR library to pick up latest fixes.

### ISSUE THREAD

**Issue by Bodobolero** [Seeed-Studio/Seeed_Arduino_LIS3DHTR#6]
**Describe the bug**
See https://github.com/arduino-libraries/Arduino_SensorKit/issues/32#issuecomment-1113482995

The latest released library released in Nov. 20 https://github.com/Seeed-Studio/Seeed_Arduino_LIS3DHTR/releases/tag/v1.2.3 does not yet pick up latest fixes like https://github.com/Seeed-Studio/Seeed_Arduino_LIS3DHTR/commit/c56da9d58d5477ac14efd190d05579f797d2edb8

This causes the Arduino Sensor Kit (Seeed product) sensors to become incompatible with newer boards based on RP2040 microcontroller using the mbed_nano architecture - for example the Arduino Nano RP2040 connect.

See https://github.com/arduino-libraries/Arduino_SensorKit/issues/32

**Comment by lakshanthad** [comment]
Hello @Bodobolero,

https://github.com/Seeed-Studio/Seeed_Arduino_LIS3DHTR/releases/tag/v1.2.4

It is done. Enjoy!

**Comment by Bodobolero** [comment]
> Hello @Bodobolero,
> 
> https://github.com/Seeed-Studio/Seeed_Arduino_LIS3DHTR/releases/tag/v1.2.4
> 
> It is done. Enjoy!

Thanks a lot
