### ISSUE TITLE
Issues connecting Grove - ADXL345 - 3-Axis Digital Accelerometer(±16g) to Arduino UNO R3

### ISSUE THREAD

**Issue by mikekenn** [Seeed-Studio/Seeed_Arduino_LIS3DHTR#8]
**Describe the bug**
When implementing the usage code you have provided, im getting the following error

_LIS3DHTR didn't connect._

**To Reproduce**
1. Connect the GND to the GND pin on the Arduino via jumped wire.
2. Connect the VCC to the 5V pin on the Arduino via jumped wire.
3. Connect the SDA to the SDA pin on the Arduino via jumped wire.
4. Connect the SCL to the SCL pin on the Arduino via jumped wire.
5. Deploy code from Arduino IDE to Uno
6. Open Serial Monitor

**Expected behavior**
Expected to see X, Y, Z values from accelerometer.

**Screenshots**
   
<img width="527" alt="image" src="https://github.com/user-attachments/assets/633047e1-5a90-48a0-b005-aeacdf1aece1">

**OS/IDE:**
 - iOS M1 Sequoia 15.0
 - Arduino IDE 
 - Version 2.3.3

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
